create table {0}
 ([ReportSessionId] varchar(256) NOT NULL,
  [Id] nvarchar(max) NOT NULL,
  [ParentId] nvarchar(max) NULL,
  [Subject] nvarchar(max) NULL,
  [TaskHyperlink] nvarchar(max) NULL,
  [ParentTaskHyperlink] nvarchar(max) NULL,
  [EmployeeName] nvarchar(max) NOT NULL,
  [ActiveText] nvarchar(max) NULL,
  [Performers] nvarchar(max) NULL,
  [Observers] nvarchar(max) NULL,
  [Created] nvarchar(max) NOT NULL,
  [Deadline] nvarchar(max) NULL,
  [Status] nvarchar(max) NULL,
  [TaskId] nvarchar(max) NULL,
  [ParentTaskId] nvarchar(max) NULL)